// Realistic Ghana-flavoured sample data for local development & demos.
// Coordinates are approximate Accra-area landmarks used only for the map demo.

export const SCHOOL = {
  name: 'Awabus Demo School',
  code: 'AWA-001',
  address: 'East Legon, Accra, Ghana',
  contactEmail: 'info@awabusdemoschool.edu.gh',
  contactPhone: '+233302123456',
  timezone: 'Africa/Accra',
  status: 'Active',
};

export const ADMIN = {
  name: 'Ama Kzyei',
  phone: '+233244528983',
  email: 'itsawabus@gmail.com',
  password: 'Awabus@123',
  role: 'admin',
};

export const PLACES = {
  Legon: { lat: 5.6519, lng: -0.1870 },
  Madina: { lat: 5.6837, lng: -0.1652 },
  Adenta: { lat: 5.7095, lng: -0.1554 },
  Oyarifa: { lat: 5.737, lng: -0.139 },
  EastLegon: { lat: 5.6508, lng: -0.147 },
  Shiashie: { lat: 5.6295, lng: -0.1665 },
  Ashongman: { lat: 5.72, lng: -0.22 },
  WestLegon: { lat: 5.665, lng: -0.205 },
  Achimota: { lat: 5.618, lng: -0.235 },
  Dome: { lat: 5.635, lng: -0.228 },
  Tesano: { lat: 5.605, lng: -0.228 },
  Dansoman: { lat: 5.539, lng: -0.268 },
  Spintex: { lat: 5.63, lng: -0.13 },
  TemaCommunity25: { lat: 5.66, lng: -0.017 },
  Kasoa: { lat: 5.533, lng: -0.417 },
  Airport: { lat: 5.6052, lng: -0.1719 },
  AirportResidential: { lat: 5.596, lng: -0.178 },
  Cantonments: { lat: 5.572, lng: -0.173 },
  Labone: { lat: 5.562, lng: -0.169 },
  Weija: { lat: 5.546, lng: -0.335 },
  Haatso: { lat: 5.667, lng: -0.202 },
  NorthKaneshie: { lat: 5.567, lng: -0.242 },
};

export const DRIVERS = [
  {
    firstName: 'Emmanuel',
    lastName: 'Mensah',
    phone: '+233244123456',
    email: 'emmanuel.mensah@awabus.com',
    dob: '1985-04-14',
    gender: 'Male',
    licenseNumber: 'GH-DL-29831',
    licenseExpiry: '2028-10-15',
    licenseClass: 'Class F (Heavy Duty / Bus)',
    emergencyContactName: 'Abena Mensah',
    emergencyContactRelation: 'Wife',
    emergencyContactPhone: '+233249991122',
    residentialAddress: 'Plot 15, Madina Estate, Accra, Ghana',
    password: 'Driver@123',
    status: 'Active',
  },
  {
    firstName: 'Samuel',
    lastName: 'Osei',
    phone: '+233208119876',
    email: 'samuel.osei@awabus.com',
    dob: '1988-02-20',
    gender: 'Male',
    licenseNumber: 'GH-DL-41220',
    licenseExpiry: '2027-06-30',
    licenseClass: 'Class F (Heavy Duty / Bus)',
    emergencyContactName: 'Yaa Osei',
    emergencyContactRelation: 'Sister',
    emergencyContactPhone: '+233201234567',
    residentialAddress: 'House 22, Adenta, Accra, Ghana',
    password: 'Driver@123',
    status: 'Active',
  },
  {
    firstName: 'Kwesi',
    lastName: 'Appiah',
    phone: '+233559331122',
    email: 'kwesi.appiah@awabus.com',
    dob: '1990-11-02',
    gender: 'Male',
    licenseNumber: 'GH-DL-10992',
    licenseExpiry: '2029-01-12',
    licenseClass: 'Class F (Heavy Duty / Bus)',
    emergencyContactName: 'Kwabena Appiah',
    emergencyContactRelation: 'Brother',
    emergencyContactPhone: '+233551239988',
    residentialAddress: 'Madina Zongo Junction, Accra, Ghana',
    password: 'Driver@123',
    status: 'Active',
  },
  {
    firstName: 'John',
    lastName: 'Dumelo',
    phone: '+233243884400',
    email: 'john.dumelo@awabus.com',
    dob: '1983-07-19',
    gender: 'Male',
    licenseNumber: 'GH-DL-38829',
    licenseExpiry: '2026-09-05',
    licenseClass: 'Class F (Heavy Duty / Bus)',
    emergencyContactName: 'Dora Dumelo',
    emergencyContactRelation: 'Wife',
    emergencyContactPhone: '+233248889900',
    residentialAddress: 'Airport Residential Area, Accra, Ghana',
    password: 'Driver@123',
    status: 'Maintenance',
  },
  {
    firstName: 'Prince',
    lastName: 'Boateng',
    phone: '+233277445511',
    email: 'prince.boateng@awabus.com',
    dob: '1992-05-08',
    gender: 'Male',
    licenseNumber: 'GH-DL-90823',
    licenseExpiry: '2028-03-21',
    licenseClass: 'Class F (Heavy Duty / Bus)',
    emergencyContactName: 'Grace Boateng',
    emergencyContactRelation: 'Wife',
    emergencyContactPhone: '+233277990011',
    residentialAddress: 'Cantonments, Accra, Ghana',
    password: 'Driver@123',
    status: 'Active',
  },
  {
    firstName: 'David',
    lastName: 'Osei',
    phone: '+233245112233',
    email: 'david.osei@awabus.com',
    dob: '1986-01-30',
    gender: 'Male',
    licenseNumber: 'GH-DL-51290',
    licenseExpiry: '2027-12-11',
    licenseClass: 'Class F (Heavy Duty / Bus)',
    emergencyContactName: 'Ama Osei',
    emergencyContactRelation: 'Wife',
    emergencyContactPhone: '+233245551122',
    residentialAddress: 'Tesano, Accra, Ghana',
    password: 'Driver@123',
    status: 'Active',
  },
  {
    firstName: 'Isaac',
    lastName: 'Mensah',
    phone: '+233209008877',
    email: 'isaac.mensah@awabus.com',
    dob: '1991-09-17',
    gender: 'Male',
    licenseNumber: 'GH-DL-77612',
    licenseExpiry: '2029-08-02',
    licenseClass: 'Class F (Heavy Duty / Bus)',
    emergencyContactName: 'Efe Mensah',
    emergencyContactRelation: 'Sister',
    emergencyContactPhone: '+233209001122',
    residentialAddress: 'Dansoman, Accra, Ghana',
    password: 'Driver@123',
    status: 'Idle',
  },
  {
    firstName: 'Robert',
    lastName: 'Lamptey',
    phone: '+233243110099',
    email: 'robert.lamptey@awabus.com',
    dob: '1984-12-25',
    gender: 'Male',
    licenseNumber: 'GH-DL-88219',
    licenseExpiry: '2028-05-19',
    licenseClass: 'Class F (Heavy Duty / Bus)',
    emergencyContactName: 'Kofi Lamptey',
    emergencyContactRelation: 'Father',
    emergencyContactPhone: '+233243009911',
    residentialAddress: 'Spintex Road, Accra, Ghana',
    password: 'Driver@123',
    status: 'Active',
  },
  {
    firstName: 'Charles',
    lastName: 'Addo',
    phone: '+233244667788',
    email: 'charles.addo@awabus.com',
    dob: '1989-06-03',
    gender: 'Male',
    licenseNumber: 'GH-DL-63142',
    licenseExpiry: '2027-02-27',
    licenseClass: 'Class F (Heavy Duty / Bus)',
    emergencyContactName: 'Grace Addo',
    emergencyContactRelation: 'Wife',
    emergencyContactPhone: '+233244118822',
    residentialAddress: 'Tema Community 25, Accra, Ghana',
    password: 'Driver@123',
    status: 'Active',
  },
  {
    firstName: 'Francis',
    lastName: 'Taylor',
    phone: '+233201112233',
    email: 'francis.taylor@awabus.com',
    dob: '1987-10-11',
    gender: 'Male',
    licenseNumber: 'GH-DL-95531',
    licenseExpiry: '2026-11-14',
    licenseClass: 'Class F (Heavy Duty / Bus)',
    emergencyContactName: 'Esi Taylor',
    emergencyContactRelation: 'Wife',
    emergencyContactPhone: '+233201119900',
    residentialAddress: 'Kasoa Highway, Accra, Ghana',
    password: 'Driver@123',
    status: 'Active',
  },
  {
    firstName: 'Yaw',
    lastName: 'Owusu',
    phone: '+233559331199',
    email: 'yaw.owusu@awabus.com',
    dob: '1993-03-15',
    gender: 'Male',
    licenseNumber: 'GH-DL-40218',
    licenseExpiry: '2029-04-09',
    licenseClass: 'Class F (Heavy Duty / Bus)',
    emergencyContactName: 'Kwesi Owusu',
    emergencyContactRelation: 'Brother',
    emergencyContactPhone: '+233559339900',
    residentialAddress: 'East Legon, Accra, Ghana',
    password: 'Driver@123',
    status: 'Idle',
  },
  {
    firstName: 'Ebenezer',
    lastName: 'Lartey',
    phone: '+233243110033',
    email: 'ebenezer.lartey@awabus.com',
    dob: '1990-08-22',
    gender: 'Male',
    licenseNumber: 'GH-DL-70044',
    licenseExpiry: '2028-07-07',
    licenseClass: 'Class F (Heavy Duty / Bus)',
    emergencyContactName: 'Kofi Lartey',
    emergencyContactRelation: 'Father',
    emergencyContactPhone: '+233243110077',
    residentialAddress: 'Airport - Spintex, Accra, Ghana',
    password: 'Driver@123',
    status: 'Active',
  },
];

export const BUSES = [
  { plateNumber: 'GC-102-21', name: 'Bus A (Cruiser)', type: 'Cruiser', capacity: 40, status: 'Active' },
  { plateNumber: 'GC-499-20', name: 'Bus B (Coaster)', type: 'Coaster', capacity: 30, status: 'Active' },
  { plateNumber: 'GT-881-19', name: 'Bus C (Standard)', type: 'Standard', capacity: 30, status: 'Idle' },
  { plateNumber: 'GC-302-22', name: 'Bus D (Cruiser)', type: 'Cruiser', capacity: 40, status: 'Maintenance' },
  { plateNumber: 'GW-118-21', name: 'Bus E (Mini)', type: 'Mini', capacity: 18, status: 'Active' },
  { plateNumber: 'GC-502-20', name: 'Bus F (Coaster)', type: 'Coaster', capacity: 30, status: 'Active' },
  { plateNumber: 'GT-221-18', name: 'Bus G (Standard)', type: 'Standard', capacity: 30, status: 'Idle' },
  { plateNumber: 'GW-402-22', name: 'Bus H (Cruiser)', type: 'Cruiser', capacity: 40, status: 'Active' },
  { plateNumber: 'GE-8821-20', name: 'Bus I (Coaster)', type: 'Coaster', capacity: 35, status: 'Active' },
  { plateNumber: 'GE-4412-19', name: 'Bus J (Standard)', type: 'Standard', capacity: 32, status: 'Active' },
  { plateNumber: 'GE-1029-22', name: 'Bus K (Cruiser)', type: 'Cruiser', capacity: 42, status: 'Active' },
  { plateNumber: 'GE-3891-21', name: 'Bus L (Mini)', type: 'Mini', capacity: 20, status: 'Idle' },
];

// Each route pairs 1:1 with DRIVERS[i] and BUSES[i] by index.
export const ROUTES = [
  { name: 'West Legon - Ashongman', from: 'WestLegon', to: 'Ashongman', status: 'Active' },
  { name: 'East Legon - Shiashie', from: 'EastLegon', to: 'Shiashie', status: 'Active' },
  { name: 'Madina - Adenta Loop', from: 'Madina', to: 'Adenta', status: 'Active' },
  { name: 'Airport Residential - Airport', from: 'AirportResidential', to: 'Airport', status: 'Inactive' },
  { name: 'Cantonments - Labone', from: 'Cantonments', to: 'Labone', status: 'Active' },
  { name: 'Tesano - Achimota', from: 'Tesano', to: 'Achimota', status: 'Active' },
  { name: 'Dansoman Loop', from: 'Dansoman', to: 'Dansoman', status: 'Inactive' },
  { name: 'Spintex Express', from: 'Spintex', to: 'TemaCommunity25', status: 'Active' },
  { name: 'Tema Community 25', from: 'TemaCommunity25', to: 'Spintex', status: 'Active' },
  { name: 'Kasoa Highway', from: 'Kasoa', to: 'Weija', status: 'Active' },
];

const GHANAIAN_FIRST_NAMES = [
  'Kwame', 'Kofi', 'Kwabena', 'Kwesi', 'Yaw', 'Kwaku', 'Yaw', 'Kojo',
  'Abena', 'Akosua', 'Efua', 'Ama', 'Esi', 'Adwoa', 'Serwaa', 'Naa',
  'Adjoa', 'Selorm', 'Kobi', 'Efia', 'Adwoa', 'Nana', 'Obed', 'Yaa',
];
const GHANAIAN_LAST_NAMES = [
  'Mensah', 'Boateng', 'Owusu', 'Asante', 'Addo', 'Osei', 'Lartey', 'Tetteh',
  'Agblo', 'Danso', 'Adjei', 'Ashiah', 'Sarpong', 'Annan', 'Darko', 'Amponsah',
];

const pick = (arr, i) => arr[i % arr.length];

export const buildStudents = (count = 36) =>
  Array.from({ length: count }).map((_, i) => {
    const first = pick(GHANAIAN_FIRST_NAMES, i);
    const last = pick(GHANAIAN_LAST_NAMES, i + 3);
    return {
      firstName: first,
      lastName: last,
      dob: new Date(2014 + (i % 6), i % 12, (i % 27) + 1),
      gender: i % 2 === 0 ? 'Male' : 'Female',
      classGrade: `${['Primary', 'JHS'][i % 2]} ${(i % 6) + 1}${['A', 'B'][i % 2]}`,
      guardianFirst: pick(GHANAIAN_FIRST_NAMES, i + 5),
      guardianLast: last,
      routeIndex: i % ROUTES.length,
      pickupTime: `${String(6 + (i % 2)).padStart(2, '0')}:${i % 2 === 0 ? '15' : '30'} AM`,
      dropoffTime: `0${3 + (i % 2)}:${i % 2 === 0 ? '45' : '30'} PM`,
    };
  });

export const TRIP_STATUSES = ['Completed', 'Completed', 'Completed', 'Delayed', 'Cancelled'];