import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { CheckCircle2 } from 'lucide-react';
import usePageHeader from '../../hooks/usePageHeader.js';
import { useCreateDraft } from '../../hooks/useFormDraft.js';
import DraftNotice from '../../components/ui/DraftNotice.jsx';
import PageHeader from '../../components/ui/PageHeader.jsx';
import Card from '../../components/ui/Card.jsx';
import Button from '../../components/ui/Button.jsx';
import RouteForm from './RouteForm.jsx';
import { createRoute } from '../../api/routes.js';
import { formatRunTime } from '../../lib/sessions.js';

const initialValues = { name: '', morningStartTime: '', eveningStartTime: '', stops: [] };

export default function AddRoute() {
  usePageHeader({ breadcrumb: ['AwaBus', 'Routes', 'Add route'] });
  const queryClient = useQueryClient();
  const [values, setValues, draft] = useCreateDraft('route:new', initialValues);
  const [created, setCreated] = useState(null);

  const mutation = useMutation({
    mutationFn: (payload) => createRoute(payload),
    onSuccess: (route) => {
      queryClient.invalidateQueries({ queryKey: ['routes'] });
      setCreated(route);
      draft.clear();
    },
  });

  const handleSubmit = (e, payload) => {
    e.preventDefault();
    mutation.mutate(payload || values);
  };

  if (created) {
    return (
      <div>
        <PageHeader title="Add route" subtitle="Establish a new transport line for the school fleet." />
        <Card className="mx-auto max-w-lg p-8 text-center">
          <CheckCircle2 className="mx-auto mb-4 h-14 w-14 text-brand-500" />
          <h2 className="text-xl font-extrabold text-slate-900 dark:text-white">Route created!</h2>
          <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
            Operational line has been listed in AwaBus roster.
          </p>
          <div className="mt-6 space-y-3 rounded-xl bg-slate-50 p-4 text-left text-sm dark:bg-navy">
            <Row label="Route ID" value={created.routeId} />
            <Row label="Route" value={created.name} />
            <Row label="Stops" value={created.stops?.length || 'None yet'} />
            <Row label="Morning pick-up" value={formatRunTime(created.morningStartTime)} />
            <Row label="Afternoon drop-off" value={formatRunTime(created.eveningStartTime)} />
            <Row label="Status" value={created.status} />
          </div>
          <p className="mt-4 text-xs text-slate-400">
            Next, register a bus and assign it to this route from the Buses page.
          </p>
          <div className="mt-6 flex justify-center gap-3">
            <Button
              variant="outline"
              onClick={() => {
                setCreated(null);
                draft.clear();
              }}
            >
              Add Routes
            </Button>
            <Button as={Link} to="/routes">
              Back to Routes
            </Button>
          </div>
        </Card>
      </div>
    );
  }

  return (
    <div>
      <PageHeader title="Add route" subtitle="Establish a new transport line for the school fleet." />
      <DraftNotice show={draft.restored} onDiscard={draft.clear} />
      <RouteForm
        mode="create"
        values={values}
        onChange={setValues}
        onSubmit={handleSubmit}
        submitting={mutation.isPending}
        routeIdDisplay="- Autogenerated"
        error={mutation.error?.message}
      />
    </div>
  );
}

const Row = ({ label, value }) => (
  <div className="flex justify-between border-b border-slate-100 pb-2 last:border-0 last:pb-0 dark:border-slate-800">
    <span className="text-slate-500 dark:text-slate-400">{label}</span>
    <span className="font-semibold text-slate-800 dark:text-slate-100">{value}</span>
  </div>
);
